CREATE TABLE [dbo].[STATUSEVENTDATE]
(
	[StatusEventDateID] INT NOT NULL PRIMARY KEY, 
    [StartTime] DATETIME NOT NULL, 
    [EndTime] DATETIME NOT NULL, 
    [StatusEventID] INT NOT NULL, 
    [LotID] INT NULL, 
    CONSTRAINT [FK_StatusEventID] FOREIGN KEY ([StatusEventID]) REFERENCES [STATUSEVENT]([StatusEventID]), 
    CONSTRAINT [FK_StatusEvent_LotID] FOREIGN KEY ([LotID]) REFERENCES [LOT]([LotID])
)
