CREATE TABLE [dbo].[LOT]
(
	[LotID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [LotName] VARCHAR(MAX) NOT NULL, 
    [LotDescription] VARCHAR(MAX) NULL, 
    [LotImageName] VARCHAR(MAX) NULL, 
    [LotImage] VARBINARY(MAX) NULL
)
