CREATE TABLE [dbo].[LOTSTATUSSCHEDULE]
(
	[LotStatusScheduleID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [LotID] INT NOT NULL, 
    [Name] VARCHAR(MAX) NULL, 
    CONSTRAINT [FK_LotID] FOREIGN KEY ([LotID]) REFERENCES [LOT]([LotID]) 
)
